In [1]:
import numpy as np
from scipy import linalg

Промисловість, сільське господарство:

In [2]:
x11 = 500
x12 = 300
y1 = 900

x21 = 150
x22 = 200
y2 = 500

x1 = x11 + x12 + y1
x2 = x21 + x22 + y2
print(x1, x2)

1700 850


Коефіцієнти матеріальних витрат, технологічна матриця

In [3]:
A = np.array([[x11/x1, x12/x2], [x21/x1, x22/x2]])
print(A)

[[0.29411765 0.35294118]
 [0.08823529 0.23529412]]


In [4]:
Y = np.array([1100,800])
print(Y)
X = np.dot(np.linalg.inv(np.eye(2) - A), Y.T)

[1100  800]


Повний випуск промислової продукції

In [5]:
X[0]

2208.8435374149662

Повний випуск с/г продукції

In [6]:
X[1]

1301.0204081632655

In [7]:
A = np.matrix([[0.5, 0.1, 0.5],
               [0, 0.3, 0.1],
               [0.2, 0.3, 0.1]])

Власні числа:

In [8]:
np.linalg.eigvals(A)

array([-0.1236068,  0.7      ,  0.3236068])

Коефіцієнти характеристичного поліному:

In [9]:
np.poly(A)

array([ 1.   , -0.9  ,  0.1  ,  0.028])

Число Фробеніуса:

In [10]:
lambda_A = max(np.linalg.eigvals(A))
print(lambda_A)

0.6999999999999995


Правий вектор Фробеніуса:

In [33]:
A1 = A - np.eye(3) * lambda_A
print(A1)
print(np.abs(A1[:,0]).T)
print()

C = A - np.eye(3) * lambda_A
print(C)
b = np.array([0, 0, 0])
x = np.linalg.eig(A.T)
print(x)
# np.allclose(np.dot(C, x), b)

[[-0.2  0.1  0.5]
 [ 0.  -0.4  0.1]
 [ 0.2  0.3 -0.6]]
[[0.2 0.  0.2]]

[[-0.2  0.1  0.5]
 [ 0.  -0.4  0.1]
 [ 0.2  0.3 -0.6]]
(array([-0.1236068,  0.7      ,  0.3236068]), matrix([[-0.26160934,  0.57735027,  0.14087505],
        [-0.51592919,  0.57735027, -0.98220003],
        [ 0.81570682,  0.57735027, -0.12424701]]))


Лівий вектор Фробеніуса:

In [29]:
A2 = A.T - np.eye(3) * lambda_A
print(A2)
print()
print(np.abs(A2[:,0]).T)
print()

x = np.linalg.solve(A.T - np.eye(3) * lambda_A, np.array([0, 0, 0]))
print(x)

[[-0.2  0.   0.2]
 [ 0.1 -0.4  0.3]
 [ 0.5  0.1 -0.6]]

[[0.2 0.1 0.5]]

[ 0. -0.  0.]


Число Фробеніуса < 1, отже, матриця A продуктивна

B - матриця повних матеріальних витрат

In [25]:
E = np.eye(3)
B = np.linalg.inv(E - A)
print(B)

t0 = E
t1 = E + A
A_i = A

i = 0
while (np.any(np.abs(t1-t0) > 0.01)):
    i = i + 1
    t0 = t1
    A_i = np.dot(A, A_i)
    t1 = E + A_i

print("Збіжний: {} ітерацій".format(i))

[[2.63157895 1.05263158 1.57894737]
 [0.0877193  1.53508772 0.21929825]
 [0.61403509 0.74561404 1.53508772]]
Збіжний: 9 ітерацій


Матриця А продуктивна

ряд Е + А + A^2 + A^3 - збіжний

Вектор цін

In [14]:
s = np.array([0.2, 0.3, 0.4])
p = s @ B
print(p)

[[0.79824561 0.96929825 0.99561404]]
